apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
  labels:
    app: helloworld
    env: dev
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        env: dev
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/baluprasanthm/helloworld:v2
        ports:
        - name:  http
          containerPort: 8080
          protocol: TCP
