name: Build and push Image ACR
on: 
 workflow_dispatch
permissions:
 id-token: write
 contents: read

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: setup JDK17
    uses: action/setup-java@v3
    with:
      java-version: '17'
      distribution: 'temurin'
      cache: maven
  - name: build with maven
    run: mvn clean package jib:build -Djib.to.auth.username= ${{ github.actor}} -Djib.to.auth.password=${{secrets.TOKEN_GITHUB}}  --file pom.xml
